name: Build and Publish Python Package

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

env:
  TARGET_PYTHON_VERSION: '3.11'

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.12", "3.11"]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test and Build
        uses: ./.github/actions/test-and-build
        with:
          python-version: ${{ matrix.python-version }}

      - name: build and publish package
        if: matrix.python-version == env.TARGET_PYTHON_VERSION
        shell: bash
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
